# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b8ab79758e298745a92f136c5f28d09e541fdd46d64b63d9f821e6582549cce9ad47631e13c26b35b129a50cd1be6a9506a1849a8616e7212536c90cd94535

test:
  secret_key_base: b9f345233c324bdbbb99d741216587c55c28b8cf606860794e2614ad8cb28234da3e38b164edc1083ec9776670f9aea1722cdafa2563393e7615ca0812d2cb4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
